service: kortoon-rest-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

functions: # for crud operations
  create:
    handler: handler.create # point to exported create function in handler.js
    events: 
      - http:
          path: kortoons # path will be ${domain}/${stage}/kortoons e.g example.com/dev/kortoons
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: kortoons/{id} # path will be ${domain}/${stage}/kortoons/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events: 
      - http: 
          path: kortoons 
          method: get
          cors: true
  update:
    handler: handler.update
    events: 
      - http:
          path: kortoons/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events: 
      - http:
          path: kortoons/{id}
          method: delete
          cors: true
          


plugins: 
  - serverless-offline