service: kortoon-rest-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

functions: # for crud operations

  getKortoons:
    handler: handler.getKortoons
    events:
      - http:
          path: kortoons/provider/{providerId}
          method: get
          cors: true
  getKortoon:
    handler: handler.getKortoon
    events:
      - http: 
          path: kortoons/provider/{providerId}/kortoon
          method: get
          cors: true
  getEpisodeScenes:
    handler: handler.getEpisodeScenes
    events:
      - http: 
          path: kortoons/provider/{providerId}/scenes
          method: get
          cors: true
          

plugins: 
  - serverless-offline